name: Lint and Test

on:
  - push
  - pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          make install
          pip install PyYAML pytest pytest-cov ruff

      - name: Run linter
        run: |
          make lint
      - name: Run tests with coverage
        run: |
          pytest --cov=gendiff --cov-report=xml tests/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.host.url=https://sonarcloud.io
              -Dsonar.projectKey=Vitalmet_python-project-50
              -Dsonar.organization=vitalmet
              -Dsonar.python.coverage.reportPaths=coverage.xml
              -Dsonar.sources=gendiff
              -Dsonar.tests=tests
              -Dsonar.coverage.exclusions=**/__init__.py,**/__main__.py
              -Dsonar.branch.name=main
